server:
  port: 8050
spring:
  application:
    name: feign
eureka:
  client:
    service-url:
      defaultZone: http://39.105.210.162:8761/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true  #是否开启熔断器